pipeline {
    agent any
    tools {
        maven 'maven-3.9.6'
        jdk 'ZULU8'
    }

    environment {
        MAVEN_REPO = "${env.HOME}/.m2/repository"
    }

    stages {
        stage('Pull repository from server') {
            steps {
                sh 'curl -O http://ae-scanner/repository/org/dita-ot'
            }
        }

        stage('Move repository to Maven repository folder') {
            steps {
                sh 'mkdir -p $MAVEN_REPO/org'
                sh 'mv dita-ot $MAVEN_REPO/org/dita-ot'
            }
        }

        stage('Build') {
            steps {
                withMaven(maven: 'maven-3.9.6') {
                    sh 'mvn -B clean install'
                }
            }
        }
    }
}
