pipeline {
    agent any
    tools {
        maven 'maven-3.6.3'
        jdk 'ZULU8'
    }

    environment {
        MAVEN_REPO = "${env.HOME}/.m2/repository"
    }

    stages {
        stage('Pull repository from server') {
            steps {
                sh 'wget -r -np -nH --cut-dirs=3 -R "index.html*" http://ae-scanner/repository/org/dita-ot/'
            }
        }

        stage('Prepare Maven repository folder') {
            steps {
                sh 'mkdir -p $MAVEN_REPO/org'
                sh 'rm -rf $MAVEN_REPO/org/dita-ot/*'
            }
        }

        stage('Move repository to Maven repository folder') {
            steps {
                sh 'mv dita-ot $MAVEN_REPO/org/dita-ot'
            }
        }

        stage('Build') {
            steps {
                withMaven(maven: 'maven-3.6.3') {
                    sh 'mvn -B clean install'
                }
            }
        }
    }
}
